### ISSUE TITLE
question

### ISSUE THREAD

**Issue by aldolala** [deanbarrow/nightTab-sync-server#1]
Hi,
I follow nighttab/hexagontab. A method to self-host this could be wonderful.
My tricky part is : Assume, I need to update data.js and/or state.js , twice a week and 52 weeks a year.
You can see this as 'my customized public startwebpage' without ADD/EDIT/SETTINGS button.
I have zero-knowledge of code and i am asked to change constantly variables in src/data and/or state.js without errors.
Then run a build and refresh hosting-server.
With your sync-server, could there be a way to make things work differently? I run 'MY' instance as a template with the power of the GUI, make the bi-weekly modifications.
Run a sync command. Push that NewData to external server and ready to get published.
Visitor to 'Mywebpage' get new content and can move on. Thx for reading
PS: when my question is too abstract not tangible enough, tell me.

**Comment by deanbarrow** [comment]
Hi @aldolala,

This sounds like it would work and would make maintaining your public start page a lot easier.
Obviously you would need to learn how to code to make the modifications or hire someone but here's an overview of how it would work.

On the sync server you would need to create a new endpoint which doesn't require authentication, for example `GET /public`. This would simply return the `data.json` file.

On the nightTab side you would need to make your own 'read only' fork based off of my fork as the PR hasn't been merged yet:
https://github.com/deanbarrow/nightTab

This would allow sync server support but you would need to make the following changes:
- Disable local data storage
- Disable the settings menu (not required but makes sense to)
- On load, request data from your new `/public` endpoint then populate the page

You can then build and upload this to your server and not have to worry about updating the data/state manually.

To make changes, setup your own version of [my fork](https://github.com/deanbarrow/nightTab) along with the sync server, any time you make a change on this new version it will be reflected to the read only version via the public endpoint.

I hope this helps.

**Comment by aldolala** [comment]
Hi Dean,
I really really appreciate your reply. For the first time a coder/developer
making the effort to read & think along.
(ZombieFox once replied that 1.being a front-end developer 2. my 'end' goal
required a back-end development.....)
Already contacted 3 different parties over last year under slogan 'You're
good with us. We make everything with simple lines of code'. (LOL)
Or I have to face my own things differently: my questions, views or
workarounds don't fit with the way developers think/work/develop.
Probably my lack of IT and code structure knowledge. Putting into words, in
correct conception is hard....I daily do Dutch, sometimes French!

So, if  this sounds 'auwch..fundamentals present. Last mile to build', but
where/what is the end goal? and YOU are willing to dive into (and finalize
a working 'better than a prototype', before 1 june 2021) then i am pretty
sure i can talk about financial compensation.

PS: this is not an 1 April fish!
Have a good day.


Op do 1 apr. 2021 om 08:29 schreef Dean ***@***.***>:

**Comment by deanbarrow** [comment]
No need to thank me, I'm happy to share my thoughts.

Some might argue that this isn't the best solution but I don't know enough about your project however if you're simply creating a "list of bookmarks" then there are probably better ways to achieve it.
If you like the aesthetic and use of this frontend then it might be worth the investment to build upon it to meet your goals.

You're welcome to reach out to me on the email on my profile, I won't guarantee I will take on the project but we can start a discussion at least.
